import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import projectsRouter from "./projects";
import buildingRouter from "./building";
import dashboardRouter from "./dashboard";
import { projectVersionsRouter } from "./versions";
import versionRouter from "./versions";
import { versionProductsRouter, productRouter } from "./products";
import { bimImportRouter } from "./bimImport";
import emissionFactorsRouter from "./emissionFactors";
import tenantEmissionFactorsRouter from "./tenantEmissionFactors";
import emissionSourcesRouter from "./emissionSources";
import validationRouter from "./validation";
import calculationsRouter from "./calculations";
import { versionReportsRouter, reportDownloadRouter } from "./reports";
import auditRouter from "./audit";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/projects", projectsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/projects/:projectId/versions/:versionId/building", buildingRouter);
router.use("/projects/:projectId/versions", projectVersionsRouter);
router.use("/versions", versionRouter);
router.use("/versions/:versionId/products", versionProductsRouter);
router.use("/versions/:versionId/bim-import", bimImportRouter);
router.use("/products", productRouter);
router.use("/emission-factors", emissionFactorsRouter);
router.use("/tenant/emission-factors", tenantEmissionFactorsRouter);
router.use("/emission-sources", emissionSourcesRouter);
router.use("/versions", validationRouter);
router.use("/versions", calculationsRouter);
router.use("/versions", versionReportsRouter);
router.use("/reports", reportDownloadRouter);
router.use("/projects", auditRouter);

export default router;
